#!/usr/bin/env python3
"""
Supabase integration for TSA Tracker historical data storage.
Stores all wait time samples for long-term trend analysis.

Setup:
1. Create free Supabase project at supabase.com
2. Set SUPABASE_URL and SUPABASE_KEY env vars
3. Run: python supabase_integration.py --init
4. In app.py, call supabase_store_samples(rows) after db_insert_rows()
"""

import os
import logging
from datetime import datetime, timedelta, timezone
from typing import Dict, List, Optional
import json

try:
    from supabase import create_client, Client
except ImportError:
    print("Install supabase: pip install supabase")
    exit(1)

logger = logging.getLogger(__name__)
APP_TZ = timezone.utc

# Initialize Supabase client
SUPABASE_URL = os.getenv("SUPABASE_URL", "").strip()
SUPABASE_KEY = os.getenv("SUPABASE_KEY", "").strip()

supabase_client: Optional[Client] = None

def init_supabase() -> Optional[Client]:
    """Initialize and return Supabase client."""
    global supabase_client
    if not SUPABASE_URL or not SUPABASE_KEY:
        logger.warning("SUPABASE_URL or SUPABASE_KEY not set. Supabase disabled.")
        return None
    try:
        supabase_client = create_client(SUPABASE_URL, SUPABASE_KEY)
        logger.info("Supabase client initialized")
        return supabase_client
    except Exception as e:
        logger.error("Failed to initialize Supabase: %s", e)
        return None

def create_tables() -> None:
    """Create historical_samples table in Supabase (run once)."""
    if not init_supabase():
        return

    try:
        # Check if table exists by querying it
        supabase_client.table("historical_samples").select("*").limit(1).execute()
        logger.info("historical_samples table already exists")
        return
    except Exception as e:
        logger.info("Creating historical_samples table: %s", e)

    # Create via SQL if needed
    try:
        supabase_client.rpc("create_historical_samples_table").execute()
    except Exception as e:
        logger.error("Failed to create table: %s", e)
        logger.info("You may need to create the table manually in Supabase SQL editor:")
        logger.info("""
        CREATE TABLE historical_samples (
            id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
            airport_code TEXT NOT NULL,
            checkpoint TEXT NOT NULL,
            wait_minutes REAL NOT NULL,
            source TEXT NOT NULL,
            lane_type TEXT DEFAULT 'STANDARD',
            captured_at TIMESTAMP WITH TIME ZONE NOT NULL,
            created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
        );
        CREATE INDEX idx_airport_time ON historical_samples(airport_code, captured_at);
        """)

def supabase_store_samples(rows: List[Dict]) -> None:
    """Insert wait time samples into Supabase."""
    if not rows or not init_supabase():
        return

    try:
        data = [
            {
                "airport_code": r.get("airport_code"),
                "checkpoint": r.get("checkpoint"),
                "wait_minutes": float(r.get("wait_minutes", 0)),
                "source": r.get("source"),
                "lane_type": r.get("lane_type", "STANDARD"),
                "captured_at": r.get("captured_at"),
            }
            for r in rows
        ]
        supabase_client.table("historical_samples").insert(data).execute()
        logger.info("Stored %d samples in Supabase", len(data))
    except Exception as e:
        logger.error("Failed to store samples in Supabase: %s", e)

def get_average_wait_at_hour(airport_code: str, hour: int, days: int = 30) -> Optional[float]:
    """
    Get average wait time for a specific hour over the past N days.

    Example: get_average_wait_at_hour("LAX", 5, 30)
    Returns average of all 5am readings in the past 30 days.
    """
    if not init_supabase():
        return None

    try:
        cutoff = (datetime.now(APP_TZ) - timedelta(days=days)).isoformat()

        # Query Supabase
        response = supabase_client.table("historical_samples").select("wait_minutes").where(
            f"airport_code=eq.{airport_code}"
        ).where(
            f"captured_at.gte.{cutoff}"
        ).execute()

        rows = response.data if response else []

        # Filter by hour
        hourly_data = []
        for row in rows:
            ts = datetime.fromisoformat(row.get("captured_at", "").replace("Z", "+00:00"))
            if ts.hour == hour:
                hourly_data.append(float(row.get("wait_minutes", 0)))

        if not hourly_data:
            return None

        return sum(hourly_data) / len(hourly_data)

    except Exception as e:
        logger.error("Failed to query average wait: %s", e)
        return None

def get_peak_hours(airport_code: str, days: int = 30, top_n: int = 3) -> List[Dict]:
    """
    Get the top N busiest hours at an airport over the past N days.
    Returns list of {"hour": 0-23, "avg_wait": float}.
    """
    if not init_supabase():
        return []

    try:
        cutoff = (datetime.now(APP_TZ) - timedelta(days=days)).isoformat()

        response = supabase_client.table("historical_samples").select("captured_at, wait_minutes").where(
            f"airport_code=eq.{airport_code}"
        ).where(
            f"captured_at.gte.{cutoff}"
        ).execute()

        rows = response.data if response else []

        # Group by hour
        hourly_avg = {}
        for row in rows:
            try:
                ts = datetime.fromisoformat(row.get("captured_at", "").replace("Z", "+00:00"))
                hour = ts.hour
                wait = float(row.get("wait_minutes", 0))

                if hour not in hourly_avg:
                    hourly_avg[hour] = []
                hourly_avg[hour].append(wait)
            except:
                pass

        # Calculate averages
        hourly_results = [
            {
                "hour": h,
                "avg_wait": sum(waits) / len(waits),
                "samples": len(waits)
            }
            for h, waits in hourly_avg.items()
        ]

        # Sort by wait time, descending
        hourly_results.sort(key=lambda x: x["avg_wait"], reverse=True)
        return hourly_results[:top_n]

    except Exception as e:
        logger.error("Failed to query peak hours: %s", e)
        return []

def init_command():
    """CLI: Initialize Supabase table."""
    print("Initializing Supabase...")
    if not SUPABASE_URL or not SUPABASE_KEY:
        print("ERROR: Set SUPABASE_URL and SUPABASE_KEY environment variables")
        return 1

    client = init_supabase()
    if not client:
        print("ERROR: Failed to connect to Supabase")
        return 1

    create_tables()
    print("✓ Supabase initialized. You can now store historical data.")
    return 0

if __name__ == "__main__":
    import sys
    if len(sys.argv) > 1 and sys.argv[1] == "--init":
        sys.exit(init_command())
    else:
        print("Usage: python supabase_integration.py --init")
